-- Reconciliation migration: exact diff between local migration history and actual DB schema
-- Generated by: prisma migrate diff --from-migrations --to-schema

-- DropForeignKey
ALTER TABLE "api_keys" DROP CONSTRAINT IF EXISTS "api_keys_teamId_fkey";

-- DropForeignKey
ALTER TABLE "llm_provider_keys" DROP CONSTRAINT IF EXISTS "llm_provider_keys_teamId_fkey";

-- DropForeignKey
ALTER TABLE "webhooks" DROP CONSTRAINT IF EXISTS "webhooks_teamId_fkey";

-- DropIndex
DROP INDEX IF EXISTS "team_invitations_teamId_email_key";

-- AlterTable
ALTER TABLE "teams" ALTER COLUMN "settings" DROP NOT NULL;

-- AlterTable
ALTER TABLE "webhook_deliveries" ALTER COLUMN "deliveryId" DROP DEFAULT;

-- AddForeignKey
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_teamId_fkey"
  FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "llm_provider_keys" ADD CONSTRAINT "llm_provider_keys_teamId_fkey"
  FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_teamId_fkey"
  FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
